name: Build
on: [pull_request, push]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get update
      - run: sudo apt-get install -y build-essential gettext cmake valac libgee-0.8-dev libsqlite3-dev libgtk-3-dev libnotify-dev libgpgme-dev libsoup2.4-dev libgcrypt20-dev libqrencode-dev libgspell-1-dev libnice-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libhandy-1-dev
      - run: ./configure --with-tests --with-libsignal-in-tree
      - run: make
      - run: build/xmpp-vala-test
      - run: build/signal-protocol-vala-test
